name: CI
on: [push]

jobs:
  rubocop:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Install gems
        run: |
          bundle install --jobs 4 --retry 3
      - name: Run linters
        run: |
          rubocop --parallel
